name: CI
run-name: ${{ github.actor }} started ci
on: [push]
jobs:
  commits-check:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: npm ci
    - name: Run e2e tests
      run: npm run e2e
    - name: Run tests
      run: npm test
