name: CI
run-name: ${{ github.actor }} started ci
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
       if [ -e package-lock.json ]; then
          npm ci
        else
          npm install
       fi
    - name: Install playwright 
      run: npx playwright install
    - name: Run e2e-ci tests
      run: npm run e2e-ci
    - name: Run test-ci tests
      run: npm run test-ci
    - name: Run tests
      run: npm test
  enforce-status-checks:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Check status checks
        run: |
          # Check if the required status checks have passed
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            checks_status=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/status" \
              | jq -r '.state')

            if [ "$checks_status" != "success" ]; then
              echo "Required status checks have not passed. Cannot merge."
              exit 1
            fi
          fi
