name: CI
run-name: ${{ github.actor }} started ci
on: [push]
jobs:
  commits-check:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
       if [ -e package-lock.json ]; then
          npm ci
        else
          npm install
       fi
    - name: Run e2e tests
      run: npm run e2e
    - name: Run tests
      run: npm test
