name: Release Workflow
run-name: ${{ github.actor }} started Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag exists
        id: check_tag
        run: |
          tag_exists=$(git tag -l "${{ github.ref }}")
          echo "::set-output name=tag_exists::${tag_exists}"
      
      - name: Create or update release
        id: create_or_update_release
        uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release URL
        id: get_release_url
        run: |
          echo "::set-output name=html_url::https://github.com/${{ github.repository }}/releases/tag/${{ github.ref }}"

      - name: Get upload URL
        id: get_upload_url
        run: |
          echo "::set-output name=upload_url::https://github.com/${{ github.repository }}/releases/${{ steps.create_or_update_release.outputs.id }}/assets"
