name: Release Workflow
run-name: ${{ github.actor }} started Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release information
        id: release_info
        run: |
          echo "::set-output name=author::${{ github.actor }}"
          echo "::set-output name=date::${{ github.event.head_commit.timestamp }}"
          echo "::set-output name=version::${{ github.ref }}"
      - name: Create Release
        uses: Roang-zero1/github-create-release-action@v3.0.1
        with:
          version_regex: '^v[0-9]+\.[0-9]+\.[0-9]+'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create_issue:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New Release',
              body: `
                Author: ${{ needs.create_release.outputs.author }}
                Date: ${{ needs.create_release.outputs.date }}
                Version: ${{ needs.create_release.outputs.version }}
                Changelog: {changelog}
              `,
              labels: ['RELEASE']
            });
            console.log('Issue created:', data.html_url);
